### ISSUE TITLE
thresholds for --nodes-online

### ISSUE THREAD

**Issue by unix196** [stockholmuniversity/nagios-plugin-elasticsearch#8]
Helo
``` 
/usr/lib/nagios/plugins/check_elasticsearch_cluster.pl  --nodes-online 
# OK - Nodes online: 3

/usr/lib/nagios/plugins/check_elasticsearch_cluster.pl --nodes-online -w 2 -c 1
# CRITICAL - Nodes online: 3
```
http://www.techadre.com/content/nagios-thresholds-ranges
Script generate critical status, although with this thresholds must be OK. Is It script consider that if number of node less  than warning threshold that OK?

**Comment by simmel** [comment]
I love thresholds but I can't wrap my head around it.

Use prepend `@` to your threshold and it will work (but I have no idea why = D):
```
/usr/lib/nagios/plugins/check_elasticsearch_cluster.pl --warning '@2' --critical '@1'
# OK - Nodes online: 3
/usr/lib/nagios/plugins/check_elasticsearch_cluster.pl --warning '@3' --critical '@1'
# WARNING - Nodes online: 3
```
